# This is a generated file. Not intended for manual editing.
services:
  catalogservice.api:
    build:
      context: "/home/e.bocharnikov/RiderProjects/OrderManagementSystem"
      dockerfile: "CatalogService.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/CatalogService.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogservice.api:dev"
    ports: []
    volumes:
    - "/home/e.bocharnikov/RiderProjects/OrderManagementSystem/CatalogService.Api:/app:rw"
    - "/home/e.bocharnikov/RiderProjects/OrderManagementSystem:/src:rw"
    - "/home/e.bocharnikov/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
